openapi: 3.0.0
info:
  title: "Parking Lot Flask REST API"
  description: "An API for managing the parking lot"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  parameters:
    spot_id:
      name: "spot_id"
      description: "ID of the spot"
      in: path
      required: true
      schema:
        type: "integer"
    vehicle_id:
      name: "vehicle_id"
      description: "ID of the vehicle"
      in: path
      required: true
      schema:
        type: "integer"
    vehicle_type:
      name: "vehicle_type"
      description: "type of vehicle to be parked"
      in: path
      required: true
      schema:
        type: "string"
        enum: ["Van", "Car", "Motorcycle"]

paths:
  /spots:
    get:
      operationId: "spot.get_all"
      tags:
        - "spot"
      summary: "Get a list of all parking spots and vehicles parked"
      responses:
        "200":
          description: "successfully all returns spots"

  /spot/{spot_id}:
    get:
      operationId: "spot.get_spot"
      tags:
        - "spot"
      summary: "Read one spot"
      parameters:
        - $ref: "#/components/parameters/spot_id"
      responses:
        "200":
          description: "successfully returns one spot"

  /lot-status:
    get:
      operationId: "spot.get_lot_status"
      tags:
        - "lot-status"
      summary: "Get available spots"
      responses:
        "200":
          description: "successfully returned lot status"
  /lot-status/vans:
    get:
      operationId: "spot.get_van_count"
      tags:
        - "lot-status"
      summary: "Summary of spots occupied by vans"
      responses:
        "200":
          description: "successfully returned count of vans"

  /park/{vehicle_type}:
    post:
      operationId: "park.park"
      tags:
        - "park"
      summary: "Park a vehicle"
      parameters:
        - $ref: "#/components/parameters/vehicle_type"
      responses:
        "200":
          description: "successfully parks one vehicle"
  /unpark/{vehicle_id}:
    delete:
      operationId: "park.unpark"
      tags:
        - "park"
      summary: "Remove a vehicle from the lot"
      parameters:
        - $ref: "#/components/parameters/vehicle_id"
      responses:
        "200":
          description: "successfully deletes vehicle from lot"
